# window.yml

# 工作流程的名字
name: Build Android Product

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - v*

# 这个工作流程需要执行的任务
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          channel: 'stable'
      - run: flutter build apk --obfuscate --split-debug-info=./symbols
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: upload-android-product
          path: build/app/outputs/flutter-apk/app-release.apk